services:
  - type: web
    name: car-rental
    env: python
    branch: main
    buildCommand:  |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn btrentals.wsgi"
    autoDeploy: true
    