# Generated by Django 5.1.6 on 2025-05-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'additions',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_status', models.CharField(max_length=11)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='car_photos/')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_da', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_da', models.DateField()),
                ('end_time', models.TimeField(null=True)),
                ('pickup_loc', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additions', models.ManyToManyField(blank=True, to='rentals.additions')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.cars')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.customers')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
