# Generated by Django 5.1.6 on 2025-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'additions',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'managed': False},
        ),
    ]
