# Generated by Django 5.1.6 on 2025-02-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_additions_alter_bookings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={},
        ),
    ]
