# Generated by Django 5.1.6 on 2025-11-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_cars_car_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('peak', 'Peak')], max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='CarSeasonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_1_2_days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_3_4_days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_5_6_days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_7_plus_days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_prices', to='rentals.cars')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.season')),
            ],
            options={
                'db_table': 'car_season_prices',
                'unique_together': {('car', 'season')},
            },
        ),
    ]
