# Generated by Django 5.1.6 on 2025-11-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_season_carseasonprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('special', 'Special')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SeasonDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ranges', to='rentals.season')),
            ],
            options={
                'db_table': 'season_date_ranges',
                'ordering': ['start_date'],
            },
        ),
    ]
