# Generated by Django 5.1.6 on 2025-02-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_bookings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={},
        ),
    ]
