# Generated by Django 5.1.6 on 2025-11-12 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_season_name_seasondaterange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarFeatureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_features', to='rentals.cars')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.carfeature')),
            ],
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Small Car', 'Small Car'), ('Jeep', 'Jeep'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van'), ('Other', 'Other')], default='Sedan', max_length=20)),
                ('special_type', models.CharField(choices=[('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], default='Gas', max_length=20)),
                ('passengers', models.PositiveSmallIntegerField(default=4)),
                ('doors', models.PositiveSmallIntegerField(default=4)),
                ('luggage_capacity', models.CharField(help_text="e.g. '2 suitcases'", max_length=50)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=20)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='rentals.cars')),
            ],
        ),
    ]
