# Generated by Django 5.1.6 on 2025-02-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_bookings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': False},
        ),
    ]
